#!/usr/local/bin/perl
use Encode qw(encode decode);
use strict;
my %map=(
    0x430 => "a"
    , 0x431 => "b"
    , 0x432 => "v"
    , 0x433 => "g"
    , 0x434 => "d"
    , 0x435 => "e"
    , 0x436 => "zh"
    , 0x437 => "z"
    , 0x438 => "i"
    , 0x439 => "j"
    , 0x43A => "k"
    , 0x43B => "l"
    , 0x43C => "m"
    , 0x43D => "n"
    , 0x43E => "o"
    , 0x43F => "p"
    , 0x440 => "r"
    , 0x441 => "s"
    , 0x442 => "t"
    , 0x443 => "u"
    , 0x444 => "f"
    , 0x445 => "h"
    , 0x446 => "ts"
    , 0x447 => "ch"
    , 0x448 => "sh"
    , 0x449 => "sh"
    , 0x44A => ""
    , 0x44B => "y"
    , 0x44C => ""
    , 0x44D => "e"
    , 0x44E => "u"
    , 0x44F => "ya"
    , 0x451 => "yo"  # e -- sits outside the alphabet in utf8
    );

binmode STDOUT, ':utf8';
while (<>) {
    # binary -> chars
    my $text = decode('utf-8', $_);
    my $out;
    for (my $i=0; $i<length($text); $i++) {
	my $x=substr($text,$i,1);
	if (defined($map{ord($x)})) {
	    $out .= $map{ord($x)};
	} else {
	    $out .= $x;
	}
    }
    print $out;
}
